services:
  bot:
    build: .
    restart: unless-stopped
    network_mode: host

    command: "python /app/bot.py"

  syncer:
    build: .
    restart: unless-stopped
    network_mode: host

    command: "python /app/syncer.py"

  boards:
    build: .
    restart: unless-stopped
    network_mode: host

    command: "python /app/syncboards.py"

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    ports:
      - "3000:3000"
